### ISSUE TITLE
Pop-ups in loops

### ISSUE THREAD

**Issue by Allexxann** [lucklab/erplab#104]
### pop_epoch2continuous has insuppressable pop-up, which breaks all attempts to loop it in scripts.

Function pop_epoch2continuous has no keys to suppress question box, you have to comment corresponding lines.

<br>
#### Steps to Reproduce

1. create for-loop with pop_epoch2continuous
2. get pop-up at the first file to process

#### Actual behavior: No such thing.
<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Win10*] |
| Matlab version | [*2017a*] |
| EEGLAB version | [*14.1.2*] |
| ERPLAB version | [*7.0.0*] |

**Comment by RenzoLanfranco** [comment]
Hi, I was looking for the same thing. 

pop_epoch2continuous.m needs a parameter that allows suppressing the question box. So far, the only solution I've found is changing the erplab M file, which isn't a good one since it prevents from sharing pipelines/scripts.

**Comment by andrewxstewart** [comment]
Hi there,

Thanks for the report.

I think a call like this should work with no popup and no warning:

`EEG2 = pop_epoch2continuous(EEG,'Warning','off');`

Does that work for you?

**Comment by Allexxann** [comment]
Shouldn't that be in the help part of the function? Because it seems like noone here had any idea that's an option at all.

**Comment by RenzoLanfranco** [comment]
Thanks Stuart. Yes, that solves the issue. -- From: Andrew X StewartSent: 28 April 2020 00:48To: lucklab/erplabCc: Renzo Lanfranco; CommentSubject: Re: [lucklab/erplab] Pop-ups in loops (#104) Hi there,Thanks for the report.I think a call like this should work with no popup and no warning:EEG2 = pop_epoch2continuous(EEG,'Warning','off');Does that work for you?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Allexxann** [comment]
Okay, this is solved, the magical parameter is here:
pop_epoch2continuous(EEG,'Warning','off');

Shame it's not mentioned in the help part of the function, but whatever.

**Comment by andrewxstewart** [comment]
I agree that this parameter should already be described in the help for this function.

I have added this now, in the latest commit. This will be included in the next ERPLAB release.

See the changes here:
https://github.com/lucklab/erplab/commit/440b0e04e169cb17900c8fe1eb959a1759d194b3
