### ISSUE TITLE
Looking for 64-channel electrode scalp map for ERPlab

### ISSUE THREAD

**Issue by EMBHlab** [lucklab/erplab#110]
Preferably in a .ced file.

**Comment by andrewxstewart** [comment]
Some sample location files are in /your_folder/eeglab/sample_locs

You will need to confirm that these locations match what you used.

Here is the standard 10-20 for 81 channels:

[Standard-10-20-Cap81.ced.zip](https://github.com/lucklab/erplab/files/3432578/Standard-10-20-Cap81.ced.zip)
