### ISSUE TITLE
Error - Moving window peak-to-peak threshold

### ISSUE THREAD

**Issue by psyterri** [lucklab/erplab#113]
### Description

The function "Moving window peak-to-peak threshold" for epoched EEG file cannot be used. EEGLAB said that this function is part of the ERPLAB toolbox.

<br>
#### Steps to Reproduce

1. ERPLAB --> Artifact detection in epoched data --> Moving window peak-to-peak threshold

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
Dialogue box pops up as below.
    
    EEGLAB error
    EEGLAB error in function pop_artmwppth() at line 87:
    Index exceeds the number of array elements (1).

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Windows 10 |
| Matlab version | 2019a |
| EEGLAB version | 2019.0 |
| ERPLAB version | 7.0 |

**Comment by andrewxstewart** [comment]
Hi Psyterri,

Thanks for the report.

I would suggest trying to clear the memory of previous settings, and trying again.

You can do that with ERPLAB > Settings > ERPLAB memory settings > reset
![Reset_mem](https://user-images.githubusercontent.com/5137405/61892529-d9a60200-aec0-11e9-9f2f-2595f90b2cb7.png)

If that doesn't resolve this, could you try emailing the EEG set you have to erplabtoobox at gmail?

**Comment by psyterri** [comment]
Dear Andrew,

The function works properly now. Thank you for your help.

Best,
Terri
