### ISSUE TITLE
ERPLAB gui cannot show full pop-up window

### ISSUE THREAD

**Issue by wycalan** [lucklab/erplab#118]
### Description

I am teaching students to use erplab. But some students' computer cannot show the full pop-up window, the upper or right part of the pop-up window is missing. For example, for my computer, the right part of the pop-up window cannot show, like this:

![QQ截图20191028165417](https://user-images.githubusercontent.com/57090263/67665143-142da800-f9a4-11e9-8679-a2095536d792.png)

OS version: win10, with a resolution of 1080*1920
| Matlab version | 2016B |
| EEGLAB version | 14.1.2 |
| ERPLAB version | 7.0.0 |

**Comment by andrewxstewart** [comment]
Hi Wycalan,

Strange!
Does this still happen in the latest commit? Find it at:
https://github.com/lucklab/erplab/archive/master.zip

**Comment by wycalan** [comment]
thanks, this problem is solved in this new version of erplab.
