### ISSUE TITLE
The contents displayed in the window were incomplete in the ERPLab

### ISSUE THREAD

**Issue by Lee666666** [lucklab/erplab#142]
### Description
Just want to know how to zoom the contents of the window to display them completely. When I run EEGLAB with my laptop and created an EventList using ERPLAB > EventList > Create EEG EventList, and then I clicked the ADVANCED button. However, I couldn't see the whole contents as shown in the figure below.
![1](https://user-images.githubusercontent.com/74190074/99528852-dc900480-29d9-11eb-8ebc-326513e9b6bc.png)

<br>
#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*fill in*] |
| EEGLAB version | [*fill in*] |
| ERPLAB version | [*fill in*] |

**Comment by andrewxstewart** [comment]
The Advanced Eventlist GUI was about 800 pixels tall, and so could be cut off on some screens.

I've adjusted this a little in ERPLAB v8.1, to be around 680 pixels tall. It should now fit on almost all modern screens no problem.

Does this fix it for you?
https://github.com/lucklab/erplab/releases

**Comment by Lee666666** [comment]
> The Advanced Eventlist GUI was about 800 pixels tall, and so could be cut off on some screens.
> 
> I've adjusted this a little in ERPLAB v8.1, to be around 680 pixels tall. It should now fit on almost all modern screens no problem.
> 
> Does this fix it for you?
> https://github.com/lucklab/erplab/releases

By reducing the scaling, I have fixed it. Thanks
