### ISSUE TITLE
Matlab 2014b/2015: handle.listener error

### ISSUE THREAD

**Issue by jasonarita** [lucklab/erplab#16]
Problem
----
In [MATLAB 2014b and above](http://www.mathworks.com/help/matlab/graphics_transition/why-does-handle-listener-return-an-error-1.html), the new graphics system is based on MATLAB® objects, which do not support the use of HANDLE.LISTENER to create event listeners. To create listeners for graphics objects, use the function ADDLISTENER.

---
### Originally from: Matthew Walenski

Matthew Walenski matthew.walenski@northwestern.edu via ucdavis.edu 
Apr 1
to erplab 

Hi,

I am having trouble plotting averaged ERPS – when I select ERPLAB -> Plot ERP -> Plot ERP waveforms
I end up with only a single electrode, which is not labelled and there is no legend.
 
I get the following error message below.
 
I found a bug report for this issue (it appears to be the same issue) in EEGLAB, but saw no resolution there, only a reference to this mailing list.
I was unable to find/search the list archive at UC Davis, so I would appreciate any help or insight!
 
Best,
matt
 
 ```
---------error message----------
No constructor 'handle.listener' with matching signature found.
 
Error in neozeroaxes>plistener (line 154)
hl = handle.listener(hC, hSrc, psetact, {func, axesin});
 
Error in neozeroaxes (line 144)
plistener(axesin,'XLim',@xylim)
 
Error in ploterps (line 574)
                        neozeroaxes(1, fsaxtick, BCKGCOLOR)
 
Error in pop_ploterps (line 684)
ploterps(ERP, binArray, chanArray,  qpstyle, qMgfp, qBlc, qxscale, qyscale, qLineWidth, qisiy,
qFontSizeChan, qFontSizeLeg, qFontSizeTicks, qerrorstd,...
 
Error in pop_ploterps (line 301)
        [ERP, erpcom] = pop_ploterps(ERP, binArray, chanArray, 'AutoYlim', rAutoYlim, 'BinNum',
        rBinNum, 'Blc', blcorr,...
Error while evaluating Menu Callback
```

**Comment by percpt** [comment]
Solution
-----
Replace all HANDLE.LISTENER() calls with ADDLISTENER().

Neozeroxes.m (Line 154)
``` 
% hl = handle.listener(hC, hSrc, psetact, {func, axesin});
hl = addlistener(hC, prp, 'PostSet', func);
```

**Comment by percpt** [comment]
We need to apply this fix to the following 3 functions that use  ```handle.listener``` function:

1. [functions/neozeroaxes.m (line 154)](https://github.com/lucklab/erplab/blob/bc3e59c214bb09f8b9ad2c253253c23754c73af3/functions/neozeroaxes.m#L154)
2. [functions/neoaxescenter.m (line 183)](https://github.com/lucklab/erplab/blob/ea4e8e9323d118167969769cb17cc48013522650/functions/neoaxescenter.m#L183)
3. [functions/axescenter.m (line 188)](https://github.com/lucklab/erplab/blob/f0072b0a2aa7f1411f01f4e8eb6c16db9fb815ed/functions/axescenter.m#L188)

**Comment by percpt** [comment]
@inheniero A quick search through our code repository shows that we don't call the functions [axescenter.m](https://github.com/lucklab/erplab/search?utf8=✓&q=axescenter.m) and [neoaxescenter.m](https://github.com/lucklab/erplab/search?utf8=✓&q=neoaxescenter.m&type=Code) anymore in our working code, so how 'bout we move those 2 functions to the deprecated folder?
