### ISSUE TITLE
pop_overwritevent cannot be looped

### ISSUE THREAD

**Issue by Aleirran** [lucklab/erplab#65]
### Description

If you try to script advanced pop_editeventlist it'll pop-up overwritevent window and halt, until you press right button. Yes, there is a command line version of this, but pop-up is called from inside of pop_editeventlist and halts whole process, so it's useless.

So, how the heck should I script this? Well, I could break some erplab files, but I don't want to.
<br>
#### Steps to Reproduce

1. EEG = pop_editeventlist( EEG , 'AlphanumericCleaning', 'on', 'BoundaryNumeric', { -99}, 'BoundaryString', { 'boundary' }, 'List', '//some path/list.txt', 'SendEL2', 'EEG', 'UpdateEEG', 'on', 'Warning', 'off' );
EEG = pop_overwritevent( EEG, 'codelabel'  );
2. pop-up for overwritevent
3. ???

<br>
#### Expected behavior:
Expected some obvious way of suppressing pop-up, like 'warning' key.

<br>
#### Actual behavior:
No such thing.

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [Win 8.1] |
| Matlab version | [2015b] |
| EEGLAB version | [14.0.0] |
| ERPLAB version | [6.1.3] |

**Comment by jasonarita** [comment]
@Aleirran Thanks for letting us know. 

In the latest ERPLAB commit, I updated `pop_editeventlist` so you can pass on the input parameter for `pop_overwritevent`  via the argument to 'UpdateEEG' . 

That is, 'UpdateEEG' can now take in one of the following input parameters:
- 'on'/'askUser'  (creates pop-up window)
- 'code'  (skips pop-up window)
- 'codelabel' (skips pop-up window)
- 'binlabel' (skips pop-up window)

So now when you pass on any other valid argument besides 'on' or 'askUser' then `pop_editeventlist` should execute without the pop-up window.

So here's what your modified code should now be:
```Matlab
% Note the change to 'UpdateEEG', 'codelabel', 
%      and deletion of the explicit call to pop_overwritevent
EEG = pop_editeventlist( EEG , 'AlphanumericCleaning', 'on', 'BoundaryNumeric', { -99}, 'BoundaryString', { 'boundary' }, 'List', '//some path/list.txt', 'SendEL2', 'EEG', ...
'UpdateEEG', 'codelabel', ...
'Warning', 'off' );
```

This fixed version of `pop_editeventlist` is in the current commit of ERPLAB, so to use the function you can either [download the entire ERPLAB commit](https://github.com/lucklab/erplab/archive/master.zip), or just selectively replace your old function with the [current `pop_editeventlist.m`](https://github.com/lucklab/erplab/blob/e6c757e1ec6255711b87ef77fb57af31d89d996e/pop_functions/pop_editeventlist.m) yourself
