### ISSUE TITLE
POP_EPOCHBIN / STR2DOUBLE Bug: ERPLAB uses a non-native version of STR2DOUBLE in POP_EPOCH/POP_EPOCHBIN

### ISSUE THREAD

**Issue by jasonarita** [lucklab/erplab#8]
The builtin Matlab-native STR2DOUBLE command removes any commas when converting strings to doubles. Thus 

```
str2double('1,5') ==> '15'
```

However, STR2DOUBLE is overwritten in the EEGLAB Biosig plugin. In this BioSig version STR2DOUBLE, commas are not removed thus

```
str2double('1,5') ==> '1'  '5'
```

ERPLAB inadvertently uses the BioSig version of STR2DOUBLE in POP_EPOCH/POP_EPOCHBIN (line 280):
```
               for i= 1:bb-1
                        numbin = str2double(char(strbin{i}));   <===== STR2DOUBLE
                        tf = ismember_bc2(numbin, binArray);
               ...
 ```

If the BioSig plugin isn't installed in EEGLAB then POP_EPOCH/POP_EPOCHBIN will throw the following error:

```
Error using pop_epoch (line 229)
pop_epoch(): empty epoch range (no epochs were found).

Error in pop_epochbin (line 313)
EEG = pop_epoch( EEG, bintype, rangtime, 'newname', EEG.setname, 'epochinfo', 'yes');
```

**Comment by percpt** [comment]
**Solution 3** Replace STR2DOUBLE with STR2NUM instead. STR2NUM looks like it preserves comma separated values by placing them into separate array indices.

**Comment by LucieAman** [comment]
Hello, I have the same error. I have checked the STR2NUM/STR2DOUBLE replacement and it looks like it has been corrected in the most recent version of EEGLAB, so I don't know what else to do. Do you have a suggestion?

Lucie

**Comment by davidg622** [comment]
Hi LucieAman,

If you are experiencing this error it might be unrelated to the str2num issue. If you want me to look at your data, you can send it to me via a zipfile to this email address: drgarrett@ucdavis.edu

Best,

David

**Comment by Kwinsler** [comment]
Hi Shanjo,

So I can see a few possible issues here.

One is that it appears that you are assigning bins to an eventlist but these are not synced with your EEG data. For instance, your binlister call should look something like this to assign bins to the data (assuming you have a BDF called "bdf.txt"):
`EEG  = pop_binlister( EEG , 'BDF', [DIR '/bdf.txt'], 'SendEL2', 'EEG', 'UpdateEEG', 'on' );
`

Or like this to assign bins to the data as well as exporting an eventlist file:
`EEG = pop_binlister(EEG, 'BDF', [DIR '/bdf.txt'], 'SendEL2', 'EEG&Text', 'UpdateEEG', 'on' ,'ExportEL', eventlist_A02T2);
`

Another issue is whether you are using an appropriate BDF.  Your code has:
`bdffile = fopen('binlister_demo_1.txt'); 
`

But then in your binlister call you use another file ("filename") which is undefined (at least from the code snippet I can see). Note that you would have to create a BDF file specifically for your data.

If you need help with that or other processing steps I would recommend this very useful resource:
https://socialsci.libretexts.org/Bookshelves/Psychology/Biological_Psychology/Applied_Event-Related_Potential_Data_Analysis_(Luck)

Chapter 6 covers assigning events to bins.

Best,
-Kurt

**Comment by Kwinsler** [comment]
Hi Shanjo,

If you send me an email (kpwinsler@ucdavis.edu) I can help you when I have time. Please include the full error traceback you are getting, and if possible, your data processing script and a data file.

-Kurt
