### ISSUE TITLE
Epocs for emotiv

### ISSUE THREAD

**Issue by talhaanwarch** [lucklab/erplab#82]
Hi, greetings. I am getting error , while i was trying to import event info. I think i am doing it in a wrong way. 
My data is of 120 sec
and i want to make epocs of 5 seconds.

I am trying some thing like this
Latency	Response
5	Stop
10	Stop
15	Stop
20	Stop
25	Push
30	Push
35	Push
40	Push
45	Pull
50	Pull
55	Pull
60	Pull
65	Stop
70	Stop
75	Stop
80	Stop
85	Push
90	Push
95	Push
100	Push
105	Pull
110	Pull
115	Pull
120	Pull

**Comment by andrewxstewart** [comment]
With the Emotiv, you will need to somehow set up event triggers, so that there can be precisely-timed 'anchors' in the data to later draw your epochs from.
https://github.com/lucklab/erplab/wiki/Basic-ERPLAB-Processing-Steps
