### ISSUE TITLE
the eeg.event.field contain subfield name reserved for erplab

### ISSUE THREAD

**Issue by Xinzhu-Fang** [lucklab/erplab#98]
### Description

[*I am getting this warning with two choices given: continue as it is or overwrites.  What does this mean? What I am supposed to do*]

<br>
#### Steps to Reproduce

1. Poped up when trying to create an eventlist

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Win10*] |
| Matlab version | [*2018a*] |
| EEGLAB version | [*14_1_1*] |
| ERPLAB version | [*0_7_0*] |

**Comment by Xinzhu-Fang** [comment]
Also, the eventlist created is messy. I tried both "overwrite" and "continue as it is".
![image](https://user-images.githubusercontent.com/29473163/49170913-3db10000-f30b-11e8-9871-79ae52e86213.png)
This is what I expect
![image](https://user-images.githubusercontent.com/29473163/49170958-5e795580-f30b-11e8-818e-b2dfeacecde3.png)

**Comment by andrewxstewart** [comment]
Hi Xinzhu-Fang,

Typically, EEGLAB has EEG-set datasets with some event info in EEG.event.*
If this is a new EEG-set, it typically won't have fields in there that collide with ERPLAB's event naming convention.

If you are running something like generating new EVENTLISTs, it can be that ERPLAB writes data to EEG.event.

If your aim is to analyze data in ERPLAB, I think you are okay to overwrite EEG.event. But be aware that this will change the EEG set in memory. As always, save important data before potential changes.

**Comment by Xinzhu-Fang** [comment]
Thank you
